// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dtfqokxpfruwkjsesrdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0ZnFva3hwZnJ1d2tqc2VzcmR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzOTIzNTAsImV4cCI6MjA1Njk2ODM1MH0.yKp65LGN89GniNZ0Dnem1G199FzY3deEffZOPsZJLWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);